// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestoAdmin.Database;

#nullable disable

namespace RestoAdmin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331105032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestoAdmin.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BookingNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("BookingTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsBanquet")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorporateEvent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFamilyCelebration")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRomanticDinner")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedBalloons")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedCandles")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedChildChair")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedFlowers")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedLiveMusic")
                        .HasColumnType("bit");

                    b.Property<bool>("NeedTableDecoration")
                        .HasColumnType("bit");

                    b.Property<int>("PersonsCount")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TableId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestoAdmin.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("HasRegularChild")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PreferredZone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("PrefersQuietZone")
                        .HasColumnType("bit");

                    b.Property<bool?>("PrefersWindowView")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RestoAdmin.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasChildChair")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPowerOutlet")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWindowView")
                        .HasColumnType("bit");

                    b.Property<bool>("IsQuietZone")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStageView")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVipZone")
                        .HasColumnType("bit");

                    b.Property<string>("LightingType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("NearExit")
                        .HasColumnType("bit");

                    b.Property<int>("NoiseLevel")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<int>("XPosition")
                        .HasColumnType("int");

                    b.Property<int>("YPosition")
                        .HasColumnType("int");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 2,
                            HasChildChair = false,
                            HasPowerOutlet = false,
                            HasWindowView = true,
                            IsQuietZone = false,
                            IsStageView = false,
                            IsVipZone = false,
                            LightingType = "Яркое",
                            NearExit = false,
                            NoiseLevel = 3,
                            Status = "free",
                            TableNumber = 1,
                            XPosition = 50,
                            YPosition = 50,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 4,
                            HasChildChair = false,
                            HasPowerOutlet = false,
                            HasWindowView = true,
                            IsQuietZone = false,
                            IsStageView = false,
                            IsVipZone = false,
                            LightingType = "Яркое",
                            NearExit = false,
                            NoiseLevel = 3,
                            Status = "free",
                            TableNumber = 2,
                            XPosition = 150,
                            YPosition = 50,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 2,
                            HasChildChair = false,
                            HasPowerOutlet = true,
                            HasWindowView = true,
                            IsQuietZone = false,
                            IsStageView = false,
                            IsVipZone = false,
                            LightingType = "Яркое",
                            NearExit = false,
                            NoiseLevel = 3,
                            Status = "free",
                            TableNumber = 3,
                            XPosition = 250,
                            YPosition = 50,
                            ZoneId = 1
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 4,
                            HasChildChair = true,
                            HasPowerOutlet = false,
                            HasWindowView = false,
                            IsQuietZone = false,
                            IsStageView = true,
                            IsVipZone = false,
                            LightingType = "Сценическое",
                            NearExit = false,
                            NoiseLevel = 4,
                            Status = "free",
                            TableNumber = 4,
                            XPosition = 50,
                            YPosition = 150,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 6,
                            HasChildChair = false,
                            HasPowerOutlet = false,
                            HasWindowView = false,
                            IsQuietZone = false,
                            IsStageView = true,
                            IsVipZone = false,
                            LightingType = "Сценическое",
                            NearExit = false,
                            NoiseLevel = 4,
                            Status = "free",
                            TableNumber = 5,
                            XPosition = 150,
                            YPosition = 150,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 4,
                            HasChildChair = true,
                            HasPowerOutlet = false,
                            HasWindowView = false,
                            IsQuietZone = false,
                            IsStageView = true,
                            IsVipZone = false,
                            LightingType = "Сценическое",
                            NearExit = false,
                            NoiseLevel = 4,
                            Status = "free",
                            TableNumber = 6,
                            XPosition = 250,
                            YPosition = 150,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 2,
                            HasChildChair = false,
                            HasPowerOutlet = true,
                            HasWindowView = false,
                            IsQuietZone = true,
                            IsStageView = false,
                            IsVipZone = true,
                            LightingType = "Приглушенное",
                            NearExit = false,
                            NoiseLevel = 1,
                            Status = "free",
                            TableNumber = 7,
                            XPosition = 50,
                            YPosition = 250,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 6,
                            HasChildChair = false,
                            HasPowerOutlet = true,
                            HasWindowView = false,
                            IsQuietZone = true,
                            IsStageView = false,
                            IsVipZone = true,
                            LightingType = "Приглушенное",
                            NearExit = false,
                            NoiseLevel = 1,
                            Status = "free",
                            TableNumber = 8,
                            XPosition = 150,
                            YPosition = 250,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 4,
                            HasChildChair = true,
                            HasPowerOutlet = false,
                            HasWindowView = false,
                            IsQuietZone = true,
                            IsStageView = false,
                            IsVipZone = false,
                            LightingType = "Мягкое",
                            NearExit = false,
                            NoiseLevel = 1,
                            Status = "free",
                            TableNumber = 9,
                            XPosition = 50,
                            YPosition = 350,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 6,
                            HasChildChair = false,
                            HasPowerOutlet = false,
                            HasWindowView = false,
                            IsQuietZone = true,
                            IsStageView = false,
                            IsVipZone = false,
                            LightingType = "Мягкое",
                            NearExit = false,
                            NoiseLevel = 1,
                            Status = "free",
                            TableNumber = 10,
                            XPosition = 150,
                            YPosition = 350,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 2,
                            HasChildChair = false,
                            HasPowerOutlet = false,
                            HasWindowView = false,
                            IsQuietZone = true,
                            IsStageView = false,
                            IsVipZone = false,
                            LightingType = "Мягкое",
                            NearExit = true,
                            NoiseLevel = 1,
                            Status = "free",
                            TableNumber = 11,
                            XPosition = 250,
                            YPosition = 350,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 4,
                            HasChildChair = true,
                            HasPowerOutlet = false,
                            HasWindowView = false,
                            IsQuietZone = true,
                            IsStageView = false,
                            IsVipZone = false,
                            LightingType = "Мягкое",
                            NearExit = false,
                            NoiseLevel = 1,
                            Status = "free",
                            TableNumber = 12,
                            XPosition = 350,
                            YPosition = 350,
                            ZoneId = 4
                        });
                });

            modelBuilder.Entity("RestoAdmin.Models.TableZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("TableZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Столики с панорамным видом на центральную улицу.",
                            Name = "У окна"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Столики в непосредственной близости от сцены.",
                            Name = "У сцены"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Отдельная зона с мягкими диванами, повышенным уровнем комфорта.",
                            Name = "VIP-зона"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Удаленная от сцены зона для спокойного отдыха.",
                            Name = "Тихая зона"
                        });
                });

            modelBuilder.Entity("RestoAdmin.Models.Booking", b =>
                {
                    b.HasOne("RestoAdmin.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RestoAdmin.Models.Table", "Table")
                        .WithMany("Bookings")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestoAdmin.Models.Table", b =>
                {
                    b.HasOne("RestoAdmin.Models.TableZone", "Zone")
                        .WithMany("Tables")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("RestoAdmin.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("RestoAdmin.Models.Table", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("RestoAdmin.Models.TableZone", b =>
                {
                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
